# This file was generated by GoReleaser. DO NOT EDIT.
cask "freshdocs" do
  desc "CLI tool to keep your documentation up to date with your code."
  homepage "https://github.com/Dullaz/freshdocs"
  version "0.0.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "freshdocs"

  on_macos do
    on_intel do
      url "https://github.com/dullaz/freshdocs/releases/download/v0.0.5/freshdocs_Darwin_x86_64.tar.gz",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        },
        referer: "https://github.com/Dullaz/homebrew-freshdocs",
        header: [
          "X-Version: 0.0.5",
        ]
      sha256 "47cca06ff49a67c9c1c9c1943338db406ddc3508dea5768c7f9347e44a2bb055"
    end
    on_arm do
      url "https://github.com/dullaz/freshdocs/releases/download/v0.0.5/freshdocs_Darwin_arm64.tar.gz",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        },
        referer: "https://github.com/Dullaz/homebrew-freshdocs",
        header: [
          "X-Version: 0.0.5",
        ]
      sha256 "9738cdf84f5a1cd9a7f28bdaabd8edb03026d7e2d199e7561a25d122eca31704"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dullaz/freshdocs/releases/download/v0.0.5/freshdocs_Linux_x86_64.tar.gz",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        },
        referer: "https://github.com/Dullaz/homebrew-freshdocs",
        header: [
          "X-Version: 0.0.5",
        ]
      sha256 "0c1d964d2ca3141c5eb638016e932404f38631e177a2e2ab362eb686442b2ab4"
    end
    on_arm do
      url "https://github.com/dullaz/freshdocs/releases/download/v0.0.5/freshdocs_Linux_arm64.tar.gz",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        },
        referer: "https://github.com/Dullaz/homebrew-freshdocs",
        header: [
          "X-Version: 0.0.5",
        ]
      sha256 "c52d92c672086053101ef98d66d959ef8519d18d0ebb2eeb07f6edeb1e8feb28"
    end
  end

  # No zap stanza required
end
