# This file was generated by GoReleaser. DO NOT EDIT.
cask "freshdocs" do
  desc "CLI tool to keep your documentation up to date with your code."
  homepage "https://github.com/Dullaz/freshdocs"
  version "0.0.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "freshdocs"

  on_macos do
    on_intel do
      url "https://github.com/dullaz/freshdocs/releases/download/v0.0.6/freshdocs_Darwin_x86_64.tar.gz",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        },
        referer: "https://github.com/Dullaz/homebrew-freshdocs",
        header: [
          "X-Version: 0.0.6",
        ]
      sha256 "8d8252ac379715a6bf8e8fd8ad277f5d83012a08aca8985f5edcb138660bc128"
    end
    on_arm do
      url "https://github.com/dullaz/freshdocs/releases/download/v0.0.6/freshdocs_Darwin_arm64.tar.gz",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        },
        referer: "https://github.com/Dullaz/homebrew-freshdocs",
        header: [
          "X-Version: 0.0.6",
        ]
      sha256 "ad2665ebdeea188571fb89303ecaf586b84d1a06ae4388c7f17d181c6896bc08"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dullaz/freshdocs/releases/download/v0.0.6/freshdocs_Linux_x86_64.tar.gz",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        },
        referer: "https://github.com/Dullaz/homebrew-freshdocs",
        header: [
          "X-Version: 0.0.6",
        ]
      sha256 "a912bca42f2529da8c53fb8ef7f048d8e01856a1b2861669734afb2f6a834bcf"
    end
    on_arm do
      url "https://github.com/dullaz/freshdocs/releases/download/v0.0.6/freshdocs_Linux_arm64.tar.gz",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        },
        referer: "https://github.com/Dullaz/homebrew-freshdocs",
        header: [
          "X-Version: 0.0.6",
        ]
      sha256 "686e39c68a827bc3a6dfa64bf5cf373e5abb159b2d8fda7cc6380c7f42dfc763"
    end
  end

  # No zap stanza required
end
